---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: regapp-secrets
  namespace: regapp
spec:
  target:
    name: regapp-secrets
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: regapp/regapp
