---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: regapp-tls
  namespace: regapp
spec:
  target:
    name: regapp-tls
    template:
      type: kubernetes.io/tls
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: regapp/regapp-tls
