# Generated by Django 3.2.5 on 2021-10-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountaction',
            name='opcode',
            field=models.CharField(choices=[('create', 'create'), ('update_verify_new_email', 'update with email change'), ('update', 'update')], default='create', max_length=32),
        ),
    ]
