# Generated by Django 3.2.5 on 2021-11-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0002_alter_accountaction_opcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountaction',
            name='research_domain',
            field=models.CharField(choices=[('social_sciences', 'Social Sciences'), ('business_management', 'Business/Management'), ('physical_sciences', 'Physical Sciences'), ('public_health_medicine', 'Public Health/Medicine'), ('stats_math', 'Statistics/Math'), ('engineering', 'Engineering'), ('arts_humanities', 'Arts/Humanities'), ('other', 'Other'), ('life_sciences', 'Life Sciences')], default='other', max_length=128),
        ),
    ]
