# Generated by Django 3.2.5 on 2021-11-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0004_auto_20211109_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountaction',
            name='opcode',
            field=models.CharField(choices=[('update_display_only', 'update display only'), ('update_verify_new_email', 'update with email change'), ('create', 'create'), ('update', 'update')], default='create', max_length=32),
        ),
        migrations.AlterField(
            model_name='accountaction',
            name='research_domain',
            field=models.CharField(choices=[('physical_sciences', 'Physical Sciences'), ('arts_humanities', 'Arts/Humanities'), ('public_health_medicine', 'Public Health/Medicine'), ('other', 'Other'), ('business_management', 'Business/Management'), ('life_sciences', 'Life Sciences'), ('engineering', 'Engineering'), ('social_sciences', 'Social Sciences'), ('stats_math', 'Statistics/Math')], default='other', max_length=128),
        ),
        migrations.AlterField(
            model_name='accountaction',
            name='sub',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
