# Generated by Django 3.2.5 on 2022-10-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0008_auto_20221013_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountaction',
            name='opcode',
            field=models.CharField(choices=[('update', 'update'), ('create', 'create'), ('update_display_only', 'update display only'), ('update_verify_new_email', 'update with email change')], default='create', max_length=32),
        ),
        migrations.AlterField(
            model_name='accountaction',
            name='research_domain',
            field=models.CharField(choices=[('other', 'Other'), ('arts_humanities', 'Arts/Humanities'), ('physical_sciences', 'Physical Sciences'), ('life_sciences', 'Life Sciences'), ('engineering', 'Engineering'), ('social_sciences', 'Social Sciences'), ('stats_math', 'Statistics/Math'), ('public_health_medicine', 'Public Health/Medicine'), ('business_management', 'Business/Management')], default='other', max_length=128),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='sub',
            field=models.CharField(default='treefort', max_length=128),
            preserve_default=False,
        ),
    ]
