# Generated by Django 3.2.5 on 2023-01-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0009_auto_20221014_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountaction',
            name='opcode',
            field=models.CharField(choices=[('update_verify_new_email', 'update with email change'), ('update_display_only', 'update display only'), ('create', 'create'), ('update', 'update')], default='create', max_length=32),
        ),
        migrations.AlterField(
            model_name='accountaction',
            name='research_domain',
            field=models.CharField(choices=[('public_health_medicine', 'Public Health/Medicine'), ('arts_humanities', 'Arts/Humanities'), ('other', 'Other'), ('stats_math', 'Statistics/Math'), ('engineering', 'Engineering'), ('business_management', 'Business/Management'), ('physical_sciences', 'Physical Sciences'), ('life_sciences', 'Life Sciences'), ('social_sciences', 'Social Sciences')], default='other', max_length=128),
        ),
    ]
