---
apiVersion: v1
kind: ConfigMap
metadata:
  name: regapp-configmap
data:
  SITENAME: regapp.apps.svc.nerc.mghpcc.org
  OIDCRedirectURI: "/"
  REGAPP_MSS_KC_SERVER: https://keycloak.apps.svc.nerc.mghpcc.org/
