---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth2-secret-cilogon
  namespace: regapp
spec:
  target:
    name: oauth2-secret-cilogon
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: regapp/oauth2proxy/cilogon
