---
# skaffold.yaml
apiVersion: skaffold/v2beta20
kind: Config
metadata:
  name: mss-skaffold
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: mghpcc/regapp
      context: ../..
      sync:
        infer:
          - "apps/**"
          - "config/**"
          - "jinja2/**"
          - "manage.py"
      docker:
        dockerfile: containers/regapp/Dockerfile
deploy:
  kustomize:
    paths:
      - overlays/microk8s

  kubeContext: k8sdev
