---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app: regapp
  name: regappdev-tls
  namespace: regapp
spec:
  dnsNames:
  - regappdev.mss.mghpcc.org
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: regappdev-tls  # noqa: E501 # pragma: allowlist secret
  usages:
    - server auth
    - client auth
