apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: regapp-root
  namespace: regapp
spec:
  host: regapp.apps.svc.nerc.mghpcc.org
  path: /
  port:
    targetPort: 8123
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: regapp
    weight: 100
  wildcardPolicy: None
